server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/ms_post_tracking
spring.datasource.username=postgres
spring.datasource.password=00023
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop

